"""empty message

Revision ID: 785880d03c12
Revises: 
Create Date: 2018-08-21 13:19:53.275642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785880d03c12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notelists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notelists')
    # ### end Alembic commands ###
